/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArrayDisplay: typeof import('./src/components/ArrayDisplay.vue')['default']
    CodeHighlight: typeof import('./src/components/CodeHighlight.vue')['default']
    DisplayLayout: typeof import('./src/layouts/DisplayLayout.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MergeCode: typeof import('./src/components/MergeCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortDisplay: typeof import('./src/components/SortDisplay.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    TwoColumns: typeof import('./src/layouts/TwoColumns.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
